---
title: "Sampling"
author: "Ziang Zhang"
date: "2024-06-19"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(Matrix)
source("code/01-state-space.R")
source("code/02-FEM.R")
source("code/03-sampling.R")
B = 100
c <- 1.1
```

## State Space Approach

Let's sample some sample paths of M-GP using the state-space method (currently only allows positive $a$):

When $a = 1/2$
```{r}
samps0 <- mGP_sim(mesh_size = 0.01, max_t = 5, alpha = 1/2, c = c)
result0 <- samps0[,1:2]
for (i in 1:B) {
  samps0 <- mGP_sim(mesh_size = 0.01, max_t = 5, alpha = 1/2, c = c)
  result0 <- cbind(result0, samps0[,2])
}
matplot(x = result0[,1], y = result0[,-1], type = 'l', ylab = "Post Samp", xlab = "x", main = "alpha = 1/2", ylim = c(-10,10))
var(result0[nrow(result0),-1])
```

When $a = 1$:
```{r}
samps1 <- mGP_sim(mesh_size = 0.01, max_t = 5, alpha = 1, c = c, sd = 1)
result1 <- samps1[,1:2]
for (i in 1:B) {
  samps1 <- mGP_sim(mesh_size = 0.01, max_t = 5, alpha = 1, c = c, sd = 1)
  result1 <- cbind(result1, samps1[,2])
}
matplot(x = result1[,1], y = result1[,-1], type = 'l', ylab = "Post Samp", xlab = "x", main = "alpha = 1", ylim = c(-10,10))
```


When $a = 1000$ (should be close to IWP):
```{r}
samps2 <- mGP_sim(mesh_size = 0.01, max_t = 5, alpha = 1000, c = c)
result2 <- samps2[,1:2]
for (i in 1:B) {
  samps2 <- mGP_sim(mesh_size = 0.01, max_t = 5, alpha = 1000, c = c)
  result2 <- cbind(result2, samps2[,2])
}
matplot(x = result2[,1], y = result2[,-1], type = 'l', ylab = "Post Samp", xlab = "x", main = "alpha = 1000", ylim = c(-10,10))
```



## Finite Element Approach

Then, let's compare with the samples drawn from the FEM approach:

When $a = 1/2$:
```{r}
xvec <- seq(0.01,5, by = 0.01)
samps <- sampling_from_FEM(x = xvec, a = 1/2, c = c, k = 100, region = c(0,5), n = B)
### Sample paths for the function
plot(samps[,1]~xvec, type = 'l', col = 1, ylab = "samps", ylim = c(-10,10))
for (i in 1:ncol(samps)) {
  lines(samps[,i]~xvec, type = 'l', col = i)
}
var(samps[length(xvec),])
```


When $a = 1$ (log):
```{r}
xvec <- seq(0.01,5, by = 0.01)
samps <- sampling_from_FEM(x = xvec, a = 1, c = c, k = 100, region = c(0,5), n = B)
### Sample paths for the function
plot(samps[,1]~xvec, type = 'l', col = 1, ylab = "samps", ylim = c(-10,10))
for (i in 1:ncol(samps)) {
  lines(samps[,i]~xvec, type = 'l', col = i)
}
var(samps[length(xvec),])
```


When $a = 1000$ (should be close to IWP):
```{r}
xvec <- seq(0.01,5, by = 0.01)
samps <- sampling_from_FEM(x = xvec, a = 1000, c = c, k = 100, region = c(0,5), n = B)
### Sample paths for the function
plot(samps[,1]~xvec, type = 'l', col = 1, ylab = "samps", ylim = c(-10,10))
for (i in 1:ncol(samps)) {
  lines(samps[,i]~xvec, type = 'l', col = i)
}
var(samps[length(xvec),])
```
